name: Manual Checkver and Commit

on:
  workflow_dispatch:

jobs:
  checkver-manual:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run checkver.ps1
        shell: pwsh
        run: |
          pwsh .\bin\checkver.ps1 idasen-systemtray -f

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        run: |
          git add bucket/idasen-systemtray.json
          git diff --cached --quiet || git commit -m "Update idasen-systemtray manifest via checkver"
          git push
