name: Manual Checkver and Commit

on:
  workflow_dispatch:

jobs:
  checkver-manual:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Remove incorrect/invalid action:
      # - uses: actions/setup-powershell@v1

      # If you need to run PowerShell commands, use shell: pwsh
      - name: Run PowerShell commands
        run: |
          # Your PowerShell commands here
          # Example:
          pwsh -Command "Write-Host 'Hello from PowerShell!'"
        shell: pwsh
