name: Manual Checkver Update

on:
  workflow_dispatch:  # Enables manual trigger from GitHub UI

jobs:
  update:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up PowerShell
        uses: actions/setup-dotnet@v3  # Optional if you need .NET for your script

      - name: Run checkver.ps1
        run: |
          .\bin\checkver.ps1 idasen-systemtray -Update

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add bucket/idasen-systemtray.json
          git commit -m "Manual update: idasen-systemtray version bump"
          git push
